import {
  CubeColorsI,
  CubePositionI,
  GenericKeyStringObject,
} from '@shared/common/interfaces';

export const CubeInitialPositions: GenericKeyStringObject<CubePositionI> = {
  t_l_F: { posX: 1, posY: 1, axes: ['A-1', 'B-1', 'C-1'] },
  t_c_F: { posX: 0, posY: 0, axes: ['A-1', 'B-2', 'C-1'] },
  t_r_F: { posX: 0, posY: 0, axes: ['A-1', 'B-3', 'C-1'] },

  c_l_F: { posX: 0, posY: 0, axes: ['A-2', 'B-1', 'C-1'] },
  c_c_F: { posX: 0, posY: 0, axes: ['A-2', 'B-2', 'C-1'] },
  c_r_F: { posX: 0, posY: 0, axes: ['A-2', 'B-3', 'C-1'] },

  b_l_F: { posX: 0, posY: 0, axes: ['A-3', 'B-1', 'C-1'] },
  b_c_F: { posX: 0, posY: 0, axes: ['A-3', 'B-2', 'C-1'] },
  b_r_F: { posX: 0, posY: 0, axes: ['A-3', 'B-3', 'C-1'] },

  t_l_M: { posX: 0, posY: 0, axes: ['A-1', 'B-1', 'C-2'] },
  t_c_M: { posX: 0, posY: 0, axes: ['A-1', 'B-2', 'C-2'] },
  t_r_M: { posX: 0, posY: 0, axes: ['A-1', 'B-3', 'C-2'] },

  c_l_M: { posX: 0, posY: 0, axes: ['A-2', 'B-1', 'C-2'] },
  c_r_M: { posX: 0, posY: 0, axes: ['A-2', 'B-3', 'C-2'] },

  b_l_M: { posX: 0, posY: 0, axes: ['A-3', 'B-1', 'C-2'] },
  b_c_M: { posX: 0, posY: 0, axes: ['A-3', 'B-2', 'C-2'] },
  b_r_M: { posX: 0, posY: 0, axes: ['A-3', 'B-3', 'C-2'] },

  t_l_B: { posX: 0, posY: 0, axes: ['A-1', 'B-1', 'C-3'] },
  t_c_B: { posX: 0, posY: 0, axes: ['A-1', 'B-2', 'C-3'] },
  t_r_B: { posX: 0, posY: 0, axes: ['A-1', 'B-3', 'C-3'] },

  c_l_B: { posX: 0, posY: 0, axes: ['A-2', 'B-1', 'C-3'] },
  c_c_B: { posX: 0, posY: 0, axes: ['A-2', 'B-2', 'C-3'] },
  c_r_B: { posX: 0, posY: 0, axes: ['A-2', 'B-3', 'C-3'] },

  b_l_B: { posX: 0, posY: 0, axes: ['A-3', 'B-1', 'C-3'] },
  b_c_B: { posX: 0, posY: 0, axes: ['A-3', 'B-2', 'C-3'] },
  b_r_B: { posX: 0, posY: 0, axes: ['A-3', 'B-3', 'C-3'] },
};

export const CubeColors: GenericKeyStringObject<CubeColorsI> = {
  t_l_F: {
    top: 'top green',
    left: 'left blue',
    front: 'front yellow',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  t_c_F: {
    top: 'top green',
    left: 'left',
    front: 'front yellow',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  t_r_F: {
    top: 'top green',
    left: 'left',
    front: 'front yellow',
    right: 'right red',
    bot: 'bot',
    back: 'back',
  },

  c_l_F: {
    top: 'top',
    left: 'left blue',
    front: 'front yellow',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  c_c_F: {
    top: 'top',
    left: 'left',
    front: 'front yellow',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  c_r_F: {
    top: 'top',
    left: 'left',
    front: 'front yellow',
    right: 'right red',
    bot: 'bot',
    back: 'back',
  },

  b_l_F: {
    top: 'top',
    left: 'left blue',
    front: 'front yellow',
    right: 'right',
    bot: 'bot white',
    back: 'back',
  },
  b_c_F: {
    top: 'top',
    left: 'left',
    front: 'front yellow',
    right: 'right',
    bot: 'bot white',
    back: 'back',
  },
  b_r_F: {
    top: 'top',
    left: 'left',
    front: 'front yellow',
    right: 'right red',
    bot: 'bot white',
    back: 'back',
  },

  t_l_M: {
    top: 'top green',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  t_c_M: {
    top: 'top green',
    left: 'left',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  t_r_M: {
    top: 'top green',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot',
    back: 'back',
  },

  c_l_M: {
    top: 'top',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back',
  },
  c_r_M: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot',
    back: 'back',
  },

  b_l_M: {
    top: 'top',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot white',
    back: 'back',
  },
  b_c_M: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right',
    bot: 'bot white',
    back: 'back',
  },
  b_r_M: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot white',
    back: 'back',
  },

  t_l_B: {
    top: 'top green',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back orange',
  },
  t_c_B: {
    top: 'top green',
    left: 'left',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back orange',
  },
  t_r_B: {
    top: 'top green',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot',
    back: 'back orange',
  },

  c_l_B: {
    top: 'top',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back orange',
  },
  c_c_B: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right',
    bot: 'bot',
    back: 'back orange',
  },
  c_r_B: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot',
    back: 'back orange',
  },

  b_l_B: {
    top: 'top',
    left: 'left blue',
    front: 'front',
    right: 'right',
    bot: 'bot white',
    back: 'back orange',
  },
  b_c_B: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right',
    bot: 'bot white',
    back: 'back orange',
  },
  b_r_B: {
    top: 'top',
    left: 'left',
    front: 'front',
    right: 'right red',
    bot: 'bot white',
    back: 'back orange',
  },
};
